site:
  title: Veidly Documentation
  url: http://localhost:8000
  start_page: veidly::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
