---
- name: Deploy Veidly to Hetzner VPS
  hosts: veidly_servers
  become: yes
  vars:
    app_user: veidly
    app_dir: /home/{{ app_user }}/app
    db_dir: /var/lib/veidly
    backup_dir: /home/{{ app_user }}/backups
    log_dir: /var/log/veidly
    
  pre_tasks:
    - name: Create application user (if doesn't exist)
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        home: /home/{{ app_user }}
        create_home: yes

    - name: Backup database before deployment
      block:
        - name: Create backup directory
          file:
            path: "{{ backup_dir }}"
            state: directory
            owner: "{{ app_user }}"
            group: "{{ app_user }}"
            mode: '0755'

        - name: Backup database
          shell: |
            TIMESTAMP=$(date +%Y%m%d_%H%M%S)
            BACKUP_FILE="{{ backup_dir }}/veidly_pre_deploy_$TIMESTAMP.db"
            if [ -f "{{ db_dir }}/veidly.db" ]; then
              sqlite3 {{ db_dir }}/veidly.db ".backup '$BACKUP_FILE'" && \
              gzip "$BACKUP_FILE" && \
              echo "Backup created: $BACKUP_FILE.gz"
            else
              echo "No database found at {{ db_dir }}/veidly.db - skipping backup"
            fi
          args:
            executable: /bin/bash
          when: ansible_check_mode == false
          register: backup_result
          failed_when: false

        - name: Display backup result
          debug:
            var: backup_result.stdout_lines
          when: backup_result is defined

  roles:
    - common
    - backend
    - frontend  
    - nginx

  post_tasks:
    - name: Verify deployment
      uri:
        url: "http://localhost:8080/api/events"
        status_code: 200
      retries: 3
      delay: 5

    - name: Display deployment info
      debug:
        msg:
          - "Deployment completed successfully!"
          - "Release: {{ release_tag }}"
          - "Domain: {{ domain }}"
          - "Backend: http://localhost:8080"
          - "Frontend: https://{{ domain }}"
          - "Logs: {{ log_dir }}"
