---
- name: Ensure npm cache directory exists with correct ownership
  file:
    path: /home/{{ app_user }}/.npm
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
    recurse: yes
  ignore_errors: yes

- name: Install npm dependencies
  npm:
    path: "{{ app_dir }}/frontend"
  become_user: "{{ app_user }}"

- name: Build frontend
  shell: |
    cd {{ app_dir }}/frontend
    npm run build
  become_user: "{{ app_user }}"
  environment:
    NODE_ENV: production
    VITE_API_URL: ""  # Use relative URLs in production (nginx proxies /api/* to backend)

- name: Ensure dist directory permissions
  file:
    path: "{{ app_dir }}/frontend/dist"
    state: directory
    owner: "{{ app_user }}"
    group: www-data
    mode: '0755'
    recurse: yes
