---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Create nginx configuration
  template:
    src: nginx-veidly.conf.j2
    dest: /etc/nginx/sites-available/veidly
    mode: '0644'
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/veidly
    dest: /etc/nginx/sites-enabled/veidly
    state: link
  notify: reload nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Test nginx configuration
  command: nginx -t
  changed_when: false

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Setup SSL with Let's Encrypt
  block:
    - name: Check if certificate exists
      stat:
        path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
      register: cert_file

    - name: Obtain SSL certificate
      command: >
        certbot --nginx
        -d {{ domain }}
        -d www.{{ domain }}
        --non-interactive
        --agree-tos
        --email {{ admin_email }}
      when: not cert_file.stat.exists

    - name: Setup certificate renewal cron
      cron:
        name: "Renew Let's Encrypt certificates"
        minute: "0"
        hour: "3"
        job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
